package com.example.exercise_one.constant

val FIRST_PLAYER_NAME = "FIRST_PLAYER_NAME"
val SECOND_PLAYER_NAME = "SECOND_PLAYER_NAME"
val FIRST_PLAYER = "FIRST_PLAYER"
val SECOND_PLAYER = "SECOND_PLAYER"